version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew build
      - run: ./gradlew test
      - run:
          name: Deploy to JitPack plaes
          command: |
            curl -X POST -H "Authorization: token jp_8djsq5v2shrm9q25b8e9djm41d" https://jitpack.io/api/builds/com.snackbars/snackbars/0.1.0-SNAPSHOT
