name: Android build

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag version
        id: increment-tag-version
        run: echo "::set-output name=tag_version::$(echo ${{ steps.get-latest-tag.outputs.latest_tag }} | awk -F '.' '{print $1+1"."$2}')"

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.increment-tag-version.outputs.tag_version }}
          release_name: Release ${{ steps.increment-tag-version.outputs.tag_version }}
          body: |
            Release ${{ steps.increment-tag-version.outputs.tag_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

