name: Tagging

on:
  push:
    branches: main

jobs:
  build:
    name: Bump tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create an incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          update_odoo_module_version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

