name: Release on JitPack

on:
  push:
    branches:
      - main # Only run on the main branch


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Get latest tag
        id: latest_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)

      - name: Increment tag
        id: inc_tag
        run: echo ::set-output name=tag::$(echo "${{ steps.latest_tag.outputs.tag }}" | awk -F. -v OFS=. '{++$NF}; print $0}')

      - name: Create tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.inc_tag.outputs.tag }}
          release_name: Release ${{ steps.inc_tag.outputs.tag }}
          body: Automatic release from Github Actions
          draft: false
          prerelease: false

      - name: Trigger JitPack build
        uses: appleboy/trigger-pipeline@main
        with:
          url: 'https://jitpack.io/api/builds/github/aqsaShahid-empglabs/SnackBars/{ref}'
          ref: ${{ steps.inc_tag.outputs.tag }}
          token: ${{ secrets.JITPACK_API_TOKEN }}
