name: Android build

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get-latest-tag
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag version
        id: increment-tag-version
        run: echo "::set-output name=tag_version::$(echo ${{ steps.get-latest-tag.outputs.latest_tag }} | awk -F '.' '{print $1+1"."$2}')"

      - name: Create tag
        uses: git-actions/create-tag@v1
        with:
          tag: ${{ steps.increment-tag-version.outputs.tag_version }}
